"""
Report generation utilities.

This module provides functionality to generate clean Markdown reports
from summarized research papers.
"""

from datetime import datetime
from typing import List, Dict
import logging
import os

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generator for Markdown research reports."""

    def __init__(self, output_dir: str = "reports"):
        """
        Initialize the report generator.

        Args:
            output_dir: Directory to save reports
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_markdown(self, papers: List[Dict]) -> str:
        """
        Generate a Markdown report from summarized papers.

        Args:
            papers: List of papers with structured Gemini insights

        Returns:
            Markdown report as string
        """
        lines = []
        
        # Title
        lines.append("# Energy Tech Innovation Report\n")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        lines.append(f"**Total Papers:** {len(papers)}\n")
        lines.append("---\n")

        # Numbered paper list
        for i, paper in enumerate(papers, 1):
            lines.append(f"## {i}. {paper.get('title', 'Unknown Title')}\n")
            
            # Authors
            authors = paper.get("authors", [])
            if authors:
                authors_str = ", ".join(authors)
                lines.append(f"**Authors:** {authors_str}\n")
            
            # Published date
            published_date = paper.get("published_date")
            if published_date:
                lines.append(f"**Published:** {published_date.strftime('%Y-%m-%d')}\n")
            
            # PDF link
            pdf_link = paper.get("pdf_link")
            if pdf_link:
                lines.append(f"**PDF:** [Download]({pdf_link})\n")
            
            lines.append("")
            
            # Gemini-generated insight (structured)
            gemini_insight = paper.get("gemini_insight", {})
            
            # Handle both old string format and new dict format
            if isinstance(gemini_insight, str):
                # Legacy format - just display as-is
                lines.append("**Gemini Insight:**\n")
                lines.append(f"{gemini_insight}\n")
            elif isinstance(gemini_insight, dict):
                # New structured format
                lines.append("### Insight Summary\n")
                insight_summary = gemini_insight.get("insight_summary", "")
                if insight_summary:
                    lines.append(f"{insight_summary}\n")
                else:
                    lines.append("*No insight summary available.*\n")
                
                # Key Innovations
                key_innovations = gemini_insight.get("key_innovations", [])
                if key_innovations:
                    lines.append("\n**Key Innovations:**\n")
                    for innovation in key_innovations:
                        lines.append(f"- {innovation}\n")
                
                # Novel Methods / Techniques
                novel_methods = gemini_insight.get("novel_methods", [])
                if novel_methods:
                    lines.append("\n**Novel Methods / Techniques:**\n")
                    for method in novel_methods:
                        lines.append(f"- {method}\n")
                
                # Potential Applications
                potential_applications = gemini_insight.get("potential_applications", [])
                if potential_applications:
                    lines.append("\n**Potential Applications:**\n")
                    for app in potential_applications:
                        lines.append(f"- {app}\n")
                
                # Extracted Keywords
                extracted_keywords = gemini_insight.get("extracted_keywords", [])
                if extracted_keywords:
                    keywords_str = ", ".join(extracted_keywords)
                    lines.append(f"\n**Extracted Keywords:** {keywords_str}\n")
            else:
                # Fallback
                lines.append("**Gemini Insight:** *No insight data available.*\n")
            
            lines.append("---\n")

        # Footer
        lines.append(f"\n*Report generated by Research-Auto*\n")

        return "\n".join(lines)

    def save_report(self, papers: List[Dict]) -> str:
        """
        Generate and save a Markdown report to file.

        Args:
            papers: List of papers with summaries

        Returns:
            Path to saved report file
        """
        filename = "reasearch_report.md"
        filepath = os.path.join(self.output_dir, filename)

        markdown = self.generate_markdown(papers)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(markdown)

        logger.info(f"Report saved to: {filepath}")
        return filepath
